<?php
/**
 * PricelistListPriceListsResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Pricelist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Pricelist\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PricelistListPriceListsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description PricelistListPriceListsResponse
 * @package     GeminiCommerce\Pricelist
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PricelistListPriceListsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PricelistListPriceListsResponse"
     */
    public function testPricelistListPriceListsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pricelists"
     */
    public function testPropertyPricelists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_page_token"
     */
    public function testPropertyNextPageToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
