<?php
/**
 * PriceListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Pricelist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Pricelist\Test\Api;

use \GeminiCommerce\Pricelist\Configuration;
use \GeminiCommerce\Pricelist\ApiException;
use \GeminiCommerce\Pricelist\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PriceListApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Pricelist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PriceListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPriceList
     *
     * Create new list.
     *
     */
    public function testCreatePriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePriceListItems
     *
     * Get prices for items.
     *
     */
    public function testDeletePriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFullPriceItemsByPricelistId
     *
     * List detailed items.
     *
     */
    public function testGetFullPriceItemsByPricelistId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPriceList
     *
     * Get specific list.
     *
     */
    public function testGetPriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPriceListByCode
     *
     * Get list by code.
     *
     */
    public function testGetPriceListByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPriceListItems
     *
     * Get items in list.
     *
     */
    public function testGetPriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPricesItems
     *
     * Get detailed items.
     *
     */
    public function testGetPricesItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFullPriceItemsByPricelistId
     *
     * List detailed price items for a specific price list.
     *
     */
    public function testListFullPriceItemsByPricelistId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPriceLists
     *
     * List all price lists.
     *
     */
    public function testListPriceLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPriceItemsByPriceListItemIds
     *
     * .
     *
     */
    public function testPriceListGetPriceItemsByPriceListItemIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setPriceListItems
     *
     * Set items in list.
     *
     */
    public function testSetPriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePriceList
     *
     * Update list.
     *
     */
    public function testUpdatePriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
