<?php
/**
 * PriceListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Pricelist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Pricelist\Test\Api;

use \GeminiCommerce\Pricelist\Configuration;
use \GeminiCommerce\Pricelist\ApiException;
use \GeminiCommerce\Pricelist\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PriceListApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Pricelist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PriceListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for priceListCreatePriceList
     *
     * .
     *
     */
    public function testPriceListCreatePriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListDeletePriceListItems
     *
     * .
     *
     */
    public function testPriceListDeletePriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetFullPriceItemsByPricelistId
     *
     * .
     *
     */
    public function testPriceListGetFullPriceItemsByPricelistId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPriceItemsByPriceListItemIds
     *
     * .
     *
     */
    public function testPriceListGetPriceItemsByPriceListItemIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPriceList
     *
     * .
     *
     */
    public function testPriceListGetPriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPriceListByCode
     *
     * .
     *
     */
    public function testPriceListGetPriceListByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPriceListItems
     *
     * .
     *
     */
    public function testPriceListGetPriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListGetPricesItems
     *
     * .
     *
     */
    public function testPriceListGetPricesItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListListFullPriceItemsByPricelistId
     *
     * .
     *
     */
    public function testPriceListListFullPriceItemsByPricelistId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListListPriceLists
     *
     * .
     *
     */
    public function testPriceListListPriceLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListSetPriceListItems
     *
     * .
     *
     */
    public function testPriceListSetPriceListItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for priceListUpdatePriceList
     *
     * .
     *
     */
    public function testPriceListUpdatePriceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
